---
- name: Create mount point
  file:
    path: /efs
    state: directory
    mode: 0755
  become: true

- name: Mount efs
  mount:
    name: /efs
    src: '{{ aws_efs_mount_dns_name }}:/'
    fstype: nfs4
    opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
    state: mounted
  become: true
