---
- name: Upgrade apt packages
  apt: upgrade=yes
       update_cache=yes
  become: true

- name: Install prerequisite packages that are necessary to compile applications and gems with native extensions
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - bison
    - build-essential
    - curl
    - default-jdk
    - gcc
    - git
    - libffi-dev
    - libgdbm3
    - libgdbm-dev
    - libmysqlclient-dev
    - libncurses5-dev
    - libreadline6-dev
    - libssl-dev
    - libyaml-dev
    - ntp
    - openssl
    - python-software-properties
    - sudo
    - sysv-rc-conf
    - vim
    - zlib1g-dev
  become: true

- name: Setup regular user
  user:
    name: '{{ application_user }}'
    comment: "Container User"
    shell: /bin/bash
  become: true
