- hosts: 127.0.0.1
  user: ubuntu
  vars_files:
    - "{{tmp_dir}}/variables.yml"
  roles:
    - common
    - efs
    - imagemagick
    - openoffice
    - { role: ANXS.monit, become: yes }
    - { role: zzet.rbenv, become: yes }
    - leonidas.nvm
    - fits
    - app
